In [ ]:
import numpy as np
arr = np.random.randint(1,10,9)
arr.reshape(3,3)

array([[7, 1, 2],
       [5, 1, 8],
       [4, 5, 8]])

In [ ]:
print("Mean = ",np.mean(arr)," Median = ",np.median(arr)," Sum = ",np.sum(arr)," Standard Deviation = ",np.std(arr))

Mean =  4.555555555555555  Median =  5.0  Sum =  41  Standard Deviation =  2.629368792488718


In [ ]:
arr1 = np.random.randint(1,100,4)
arr1.reshape(2,2)

array([[ 8, 93],
       [32, 85]])

In [ ]:
arr2 = np.arange(1,9,2)
arr2.reshape(2,2)

array([[1, 3],
       [5, 7]])

In [ ]:
print(np.dot(arr1,arr2))

1042


In [ ]:
print(arr1[arr1%2==0],arr1[arr1%2!=0])

[ 8 32] [93 85]
